//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RojgarMitraWebApi.DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMaster()
        {
            this.UserEmployementDetails = new HashSet<UserEmployementDetail>();
            this.UserEducationDetails = new HashSet<UserEducationDetail>();
        }
    
        public long UserID { get; set; }
        public string FullName { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public string StdCode { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> TotalExYear { get; set; }
        public Nullable<int> ToalExMonth { get; set; }
        public string Resume { get; set; }
        public string CurrentLocation { get; set; }
        public string LandLineNumber1 { get; set; }
        public string LandLineNumer2 { get; set; }
        public string MobileNumber2 { get; set; }
        public string Role { get; set; }
        public Nullable<int> Prefereedocation { get; set; }
        public string PermanentAddress { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string HomeTown { get; set; }
        public Nullable<int> PinCode { get; set; }
        public Nullable<int> MartialStatus { get; set; }
        public string KeySkills { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool Active { get; set; }
        public string ProfileImage { get; set; }
        public string Extension { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEmployementDetail> UserEmployementDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEducationDetail> UserEducationDetails { get; set; }
    }
}
